server:
  error:
    include-exception: true # 오류 응답에 exception의 내용을 포함할지 여부
    include-stacktrace: always # 오류 응답에 stacktrace 내용을 포함할 지 여부
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/moritools_dev
    username: moritools
    password: 1234
  flyway:
    baseline-on-migrate: true
  messages:
    basename: i18n/messages
mybatis:
  mapper-locations: mybatis/mapper/**/*.xml
logging:
  level:
    root: info
    jdbc: off
    jdbc.connection: off
    jdbc.sqlonly: debug
    jdbc.sqltiming: off
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.resultsettable: debug
    com.noonibox.wc: trace
